# Generated by Django 3.2.9 on 2021-11-09 02:24

import pymilvus.client.types
from django.db import migrations

import django_milvus.fields
import django_milvus_tests.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_milvus_tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="largefield",
            field=django_milvus.fields.MilvusField(
                dbname="default",
                default=django_milvus_tests.models.random_vector_16,
                dim=16,
                dtype=pymilvus.client.types.DataType["FLOAT_VECTOR"],
                index_type="IVF_FLAT",
                metric_type="L2",
                nlist=1024,
                nprobe=32,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="similarity",
            field=django_milvus.fields.MilvusField(
                dbname="default",
                default=django_milvus_tests.models.random_vector_2,
                dim=2,
                dtype=pymilvus.client.types.DataType["FLOAT_VECTOR"],
                index_type="IVF_FLAT",
                metric_type="L2",
                nlist=1024,
                nprobe=32,
            ),
        ),
    ]
