# Generated by Django 3.2.9 on 2021-12-30 18:13

import pymilvus.client.types
from django.db import migrations, models

import django_milvus.fields
import django_milvus_tests.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_milvus_tests", "0002_auto_20211109_0224"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUUID",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "similarity",
                    django_milvus.fields.MilvusField(
                        dbname="default",
                        default=django_milvus_tests.models.random_vector_2,
                        dim=2,
                        dtype=pymilvus.client.types.DataType["FLOAT_VECTOR"],
                        index_type="IVF_FLAT",
                        metric_type="L2",
                        nlist=1024,
                        nprobe=32,
                    ),
                ),
            ],
        ),
    ]
